sudo: required
services: 
  - docker

script:
  - docker build -t richyb/node .
  - docker images richyb/node

before_deploy:
  - docker login -u "richyb" -p "Da8282pbdocker"

deploy:
  provider: script
  script: docker push richyb1982/node
  on:
    branch: master
  edge: true